language: android
sudo: required
jdk: oraclejdk8
env:
  matrix:
  - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
  global:
  - ADB_INSTALL_TIMEOUT=10
  - ANDROID_API=21
  - ANDROID_BUILD_TOOLS=25.0.2
  - secure: cXTC67OjWt2c9kUYe1p18b+ONCPV93VnjZXq5uBS/MZNq95Tn2Yo+6kWj6myMKP9XdQZXDxSPevRmBuILYPr2CLqbz5EJfcDGDtCSYpnMhny7j47s7c24sFC4v3xOLf/2NB/g9gj0Mx61h/x/AmyTZ56j/3N77KGPwN0rU9GtuCAV/XpK3l9zM2+KWk59VFeqGht8AyyCFidcxQ9auL2VLtwSwon521qAPt2bSLwQWr1bniN/6F/8/2cuAkF2b7EI1Os7yKMkZ9tkm3wAz+oVE4WF5BaoMHKAO8MO/9fzmlJLyV7Pl+gfV+cDFBD3ANTL37VqZDo40H7naIbXQEtGxHj3fDelFuB2U9Qs+aH2BfcgFNsAsdqV4vYc3BoJYg0aSdpmQEFgKY7yIvF+eWeyz+pjt/fBtHLC8EAGJ/We2IzIBAWFkil7C3T5fotGwiwZv3jqyB4rcmXkXNznm4LQZJ4AVsmNhsSCtlm3i5t/Pih/u4hjg9SWBn0LRRUYGyzoAQDajUtW7MOCLvRsoDzt8hSYnx4xcG5GiUMIqY6sd5RQZp6U9YeI6pIhxDChYs/CinVdRfprczZQqPyn5Py8+05zPn8lTdGKJ3LxvZYncPFax6XtVQj2pYNtM46zreD2Gr5PneiJ4qFLk3JVtRt4aAKAF9rMjNz/mof7wZ7mfE=
  - secure: KEtb8pK7qRDn+rAR3CFX0nX6DYxIGYTADiKl+odo+9r9wFEti0ehWGYPWqbMY+X1UzdSu3bvHTOGTlhjKmur/GuJiBPVHKV3MlG3awcImlE4rv9M5lzffXS18YRZuqd3MGbTgs9Fj2MUzWZwQDF9ADLWYJoCDq+3PNbuCouZQy7yLy4/E7aWH4FwcIFcGGEYOmURxb5rV7vPuPmjQL98CAkgjO3myL3S0ZHfdoQ1EMejzOMCEcR7D3/LQqJYWrop9m+YCBUpKKIlITk1FrPHB8Bh1Drx/GrMyKHl+rEgfvpSKHPZjwZhKcQg9vxp6XUVPVcLqES0MwjmPUQY5PXP980UmcogKg43KZyRYVww0jJAhu/FV2jeIaBi8+AbXHWMjWwbRIlTkwkjsAwrqXNKSmaaebxv0WB5cSYoNbsEvZm7UCaaXZhtJcOWhgR03XPu55XiFuMgPs6PAXRbr707qQUPClJtLA06vPJeZyeZ9yTVZZ/LBnHt7Xr5Fk8R1nljyFeOP6tk55WcWMmVyMpkgt8AR5N94DRunsbZAcu5paQQ+EelC41/VK3UzCQQqjmR3gyNrbD4fmI35KZXGF2l+aD3YItBrWcL5yZ+9UatBulkryP1rsuXPx05IJq5V6FGC8YtueZB9XIz59+jdyFaT0/GQ7sEemXAkOEtBuhgG2Y=
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/daemon"
  - "$HOME/.gradle/native"
  - "$HOME/.gradle/wrapper"
android:
  update_sdk: true
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-21
licenses:
- android-sdk-preview-license-52d11cd2
- android-sdk-license-.+
- google-gdk-license-.+
before_script:
- chmod +x gradlew
before_deploy:
  - ./gradlew assembleRelease #Se genera un apk con el nombre app-unsigned.apk en projectName/app/build/outputs/apñ
  - ls app/build/outputs/apk
  - ./zipalign -v -p 4 app/build/outputs/apk/app-unsigned.apk app/build/outputs/apk/app-unsigned-aligned.apk
  - apksigner sign --ks ClavesAndroid.jks --out app/build/outputs/apk/app-release.apk app/build/outputs/apk/app-unsigned-aligned.apk
  - apksigner verify app-release.apk

deploy:
  provider: releases
  file: app-release.apk
  skip_cleanup: true
  on:
    repo: milenaf30/JugamosTodos
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: gETXw2N8tc4IxPutqtWZSHXoTldtoI2jY3gTjw6ou1WhSz0HbMSaGAWTGfe4RsbTrC8xlAmN8JuNDpO6PCHMrdoEGrIirSn3qXIakjaHeAAzDSEOUYSDugAN8EY4+3ewAl8Z1pT8YJ7CMY81UBMGLe2YcRt8I9VADWzRupNmhilpQB6lzzkt5RGQHKznMY1bbw/OVqthyiMax4vj8h9ERJnzxCGQ4Q50dRnqFn5Iohy4E0VzLbVTSzyUSzNynmfNlIwv3/SoaimY0s50Hb+E1mE1DsV3LRHANkTKSVy3k0FI/+ihTfPiMaLTBj9k2r1ej/DyIc2auDISM8V9sD4XmXJ+wGX0/0xoxU/w7YFPskzkoG5zmFHSJFS7Jvk1+4fUyQMHQx1cxLn1BYEh5Ifl/BMgmkhbiFUG6N7ArU4hCNG9Rt2gnr0SNnwiwyrlPoqiwgLzgxIfco/oL8JL++8jvO6XLVyl9rTebq57UJBiHWfyMXVEt7Xft1GqYoBmH25v+JiGJ0pIx5hf2RghIVK8r0kfSI1nbw93F90sqTMAA96ofSBlgSt9iqQIcCpVXe5EX/F2e2EFYqyb53ejWwFevu6pif4HpcSc05yPIim67prrnAv+93/RT129pklj1M/gSKXc6WSTvXuDPJ7XI4qbtzQXh/hBqKfqJRDFmtjnTCk=
